version: '3.3'

services:
  slim-app:
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${APP_USER}'
    container_name: "${APP_NAME}-app"
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - "host._docker.internal:host-gateway"
    ports:
      - "9003:9003"
#    networks:
#      - backend
    volumes:
      - ../../../:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
  slim-nginx:
    image: nginx:1.19-alpine
    container_name: "${APP_NAME}-nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../../../:/var/www
      - ./nginx:/etc/nginx/conf.d
  slim-db:
    container_name: "${APP_NAME}-db"
    image: mysql:8.0
    volumes:
      - ../../../storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
    ports:
      - "3306:3306"
  slim-mailhog:
    container_name: "${APP_NAME}-mailhog"
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
  slim-redis:
    image: redis:latest
    container_name: "${APP_NAME}-redis"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASS}
  slim-cron:
    build:
      context: ""
      dockerfile: CronDockerfile
    container_name: "${APP_NAME}-cron"
    restart: always
#    networks:
#      - backend
    volumes:
      - ../../../:/var/www
      - ../../../storage/cron:/var/log
      - ../../../crontab:/etc/cron.d/slim

#networks:
#  backend:
#    driver: bridge
